export const COMMON_CITIES = [
    "London", "Manchester", "Liverpool", "Birmingham", "Leeds", "Newcastle", "Leicester", "Southampton",
    "Madrid", "Barcelona", "Seville", "Valencia", "Bilbao", "Malaga", "Vigo",
    "Paris", "Marseille", "Lyon", "Lille", "Bordeaux", "Monaco", "Nice",
    "Rome", "Milan", "Turin", "Naples", "Florence", "Bologna", "Genoa",
    "Berlin", "Munich", "Dortmund", "Hamburg", "Frankfurt", "Cologne", "Leipzig",
    "Buenos Aires", "Rosario", "Cordoba", "Mendoza", "La Plata", "Santa Fe",
    "Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador", "Belo Horizonte",
    "Santiago", "Valparaiso", "Concepcion",
    "Montevideo",
    "Bogota", "Medellin", "Cali", "Barranquilla",
    "Lima", "Cusco", "Arequipa",
    "Mexico City", "Guadalajara", "Monterrey", "Cancun",
    "New York", "Los Angeles", "Chicago", "Miami", "Boston", "Seattle", "Atlanta",
    "Toronto", "Vancouver", "Montreal",
    "Tokyo", "Osaka", "Kyoto", "Yokohama",
    "Beijing", "Shanghai", "Chengdu",
    "Seoul", "Busan", "Incheon",
    "Sydney", "Melbourne", "Brisbane",
    "Cairo", "Lagos", "Cape Town",
    "Istanbul", "Athens", "Lisbon", "Porto", "Amsterdam", "Rotterdam", "Brussels", "Vienna",
    "Zurich", "Geneva", "Dublin", "Edinburgh", "Glasgow", "Cardiff",
    "Copenhagen", "Stockholm", "Oslo", "Helsinki", "Warsaw", "Prague", "Budapest", "Bucharest", "Belgrade", "Zagreb"
].sort();
